### ISSUE TITLE
indexcov: Unexpectedly long run time

### ISSUE THREAD

**Issue by sjackman** [brentp/goleft#11]
I interrupted `goleft indexcov` after 43 minutes, whereas `samtools depth` completed in 2 minutes.

```
❯❯❯ time goleft indexcov foo.bam
^C interrupt
real	42m56.588s
user	44m41.414s
sys	0m26.671s
❯❯❯ time samtools depth -a foo.bam
real	2m11.683s
user	2m3.448s
sys	0m3.460s
❯❯❯ du -h foo.bam
3.0G	foo.bam
```

The BAM file is of reads aligned to a de novo assembled draft genome with 205 Mbp in 1.6 million contigs. The files reside on an NFS file system. Any thoughts?

**Comment by brentp** [comment]
hmm, any chance you can share the bam or a small chunk of it?
how big is the index?

**Comment by brentp** [comment]
is this on the goleft you built from source or on the downloaded binary?

**Comment by brentp** [comment]
oh, I see 1.6 million contigs! well, that's likely the problem.
You could run this with the `-c` flag for each of the the N largest contigs.

It would be great if I could get an example bam to try to work out this problem.

**Comment by brentp** [comment]
actually, if you can shared just the .bai index, without the bam, that would also be useful.

**Comment by sjackman** [comment]
Here's the 88 MB .bai file:
ftp://ftp.bcgsc.ca/public/sjackman/goleft/many.bam.bai

**Comment by brentp** [comment]
the latest commit to goleft along with an update to biogo/hts should improve this.

I'll continue to make improvements that will help this use-case but it's likely going to be slow as this approach will work best when the number of chromosomes/contigs is on the order of hundreds and maybe thousands .

**Comment by brentp** [comment]
actually, I hacked indexcov to run without the bam (which is only used to get the refnames) and it runs in 8 seconds so I think that's pretty good for 1.6M chromosomes.

A remaining limitation for your data is that contigs with length < 16384 wont appear in the output. There is no way to overcome this because of the resolution of the bam index.

**Comment by brentp** [comment]
closing. please re-open if you continue to have problems.

**Comment by sjackman** [comment]
Thanks, Brent!
