### ISSUE TITLE
Incorporate indexcov into MultiQC

### ISSUE THREAD

**Issue by chapmanb** [brentp/goleft#12]
Brent;
The new indexcov command and outputs are fabulous, and a brilliant way to get a quick overview of coverage across chromosomes. What would you think about outputting raw data we could incorporate into MultiQC (https://github.com/ewels/MultiQC)?

MultiQC consolidates all the outputting reporting in bcbio into a single HTML and allows displays like tabbing which we could use to provide the multiple chromosome plots. It has built in interactive charts, cutomized hiding of samples and other nice features to scale up for bigger sample sizes.

Practically this would require dumping the outputs you currently plot into tab delimited files we could suck up as a MultiQC module for indexcov (http://multiqc.info/docs/#plotting-functions). I haven't compiled and run the latest indexcov but looking at the code it looks like you might already do some of this. Thanks for considering this approach for making indexcov outputs available.

**Comment by brentp** [comment]
Yes. This is exactly what I had in mind. As you saw, I've just added a lot of stuff the last couple of days. Everything that's plotted is also output as TSV, so MultiQC should be able to consume it.

I'm now working on having it output a ped file with the sex inferred from the depth on the X chromosome. Once that's done, I'll make a release. That will be this week.

**Comment by chapmanb** [comment]
Brent;
Awesome, thanks for being on top of this idea before I even suggested it. Happy to help MultiQC integration or anything else once this is all ready. Thanks again.

**Comment by brentp** [comment]
Hi Brad, I just tagged a release that includes the improvements to indexcov. I also documented the text output here: https://github.com/brentp/goleft/tree/master/indexcov#Files

I'm happy to help in any way I can with multiqc integration and/or any problems or changes in goleft.

**Comment by brentp** [comment]
Hi Brad, not sure if you've started looking into this, but I'll also have a PCA output with the 1st 5 principal components coming soon.

**Comment by chapmanb** [comment]
Brent;
Nice, thanks for the additional metrics work. I haven't started working on this yet; I was trying to get a bcbio release out and finalizing things for that, then will tackle this for the next release. I'll definitely incorporate the additional plots once you have them in.

**Comment by brentp** [comment]
OK. Best to wait a bit anyway until the dust settles on some new features.

**Comment by brentp** [comment]
Hi Brad, the new release is out (https://github.com/brentp/goleft/releases/tag/v0.1.11) and should be fairly stable. If you want to make small example data, I
have binaries here: https://github.com/brentp/goleft/releases/download/v0.1.10/anonymize-for-indexcov_linux64
https://github.com/brentp/goleft/releases/download/v0.1.10/anonymize-for-indexcov_osx
that will create a bam that contains only the header (without read-group) and copy the bam index to sample_0001 .. sample_$n.bam / .bai.

**Comment by chapmanb** [comment]
Brent and all;
I submitted a PR to MultiQC to support by chromosome plots of coverage and ROC depth. Thanks for all the help with getting this in place, it's brilliant to have these in the bcbio MultiQC reports. I'll close out this issue when it gets merged into the main MultiQC.

**Comment by brentp** [comment]
thanks Brad!
I would recommend also showing a version of the bin plot (top right plot [here](http://indexcov.s3-website-us-east-1.amazonaws.com/) ) because it shows a summary view that will likely reflect coverage problems genome-wide. The columns are bins.lo and bins.out from the .ped file created by indexcov.

I can also make an additional PR to MultiQC once yours is incoportated as I'd like to understand that better.

**Comment by chapmanb** [comment]
Brent;
Good suggestion, thanks. I'd meant to include that and forgot. If you prefer it as an exercise than I can leave it, or push it myself and include it within the PR. It should be pretty similar to the two existing plots but with a scatter instead of lineplot. Let me know what you prefer.

**Comment by brentp** [comment]
Please go ahead

**Comment by chapmanb** [comment]
Thanks Brent -- I've incorporated that diagnostic scatter plot into the MultiQC output as well, that'll be really useful. Hopefully the commit gives a good idea about how to additional additional plots. Thanks again.

**Comment by chapmanb** [comment]
goleft ROC and bin plots are now included in the latest development version of MultiQC (https://github.com/ewels/MultiQC/pull/399). Brent, thank you for all the help getting this integrated.

**Comment by brentp** [comment]
thank you!
