### ISSUE TITLE
0.1.9 release linux binary is actually 0.1.6?

### ISSUE THREAD

**Issue by stephenturner** [brentp/goleft#13]
```
$ wget https://github.com/brentp/goleft/releases/download/v0.1.9/goleft_linux64 -O goleft
$ chmod +x goleft
$ goleft -h
goleft Version: 0.1.6

depth : parallelize calls to samtools in user-defined windows
```

**Comment by brentp** [comment]
There is a version reporting problem,  but you must have an old version of `goleft`. The download of v0.1.9 actually reports v0.1.8. :(

I will likely make a v0.1.10 soon that addresses any additional problems people find and reports the correct version. I'll leave this issue open to track that.
thanks for reporting.

**Comment by stephenturner** [comment]
ah! looks like i have goleft as part of bcbio-nextgen and that's ahead in my bin.

**Comment by brentp** [comment]
this is fixed in the new release along with other improvements: https://github.com/brentp/goleft/releases/tag/v0.1.10
