### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by nsmackler** [brentp/goleft#14]
I ran into this error:
$ goleft_linux64  indexcov --prefix merged/30J.rmdup.bam
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/brentp/goleft/indexcov.Main()
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:218 +0xe70
main.main()
	/home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:65 +0x191

Could this be due to the fact that our chromosome names are not in "chr" format? Is there any way to change the defaults so that we can use genomes without chromosomal scaffolds? Here is the output of samtools idxstats on the "30J.rmdup.bam" alignment file:
CM002977.3      225584828       8338981 465136
CM002980.3      204787373       7537439 390998
CM002984.2      185818997       6517117 332638
CM002983.2      172585720       6076609 306025
CM002981.2      190429646       6355739 298694
CM002982.3      180051392       6521339 342746
CM002991.3      169600520       6305670 350299
CM002985.3      144306982       5341132 285889
CM002987.3      129882849       4826300 276518
CM002992.3      92844088        3560246 217738
CM002989.3      133663169       4869039 254070
CM002979.2      125506784       4406793 224347
CM002978.2      108979918       4114634 231117
CM002988.2      127894412       4823764 274264
CM002986.2      111343173       4088611 220325
CM002994.2      77216781        2713115 147784
CM002990.2      95684472        3447325 168426
CM002995.2      70235451        2527018 132779
CM002996.3      53671032        1790224 86788
CM002993.2      74971481        2857223 168165
CM002997.3      149150640       5750773 315248
CM003438.1      11753682        38388   3424

Thanks,
Noah

**Comment by brentp** [comment]
```
$ goleft_linux64 indexcov --prefix merged/30J.rmdup.bam
```
if this is how you ran it, you are telling indexcov to use the bam as the prefix. it should look like:
```
$ goleft_linux64 indexcov --prefix 30J-output merged/30J.rmdup.bam
```

**Comment by nsmackler** [comment]
I just noticed that. Sorry. Closing the issue.

Thanks for the quick response!

**Comment by brentp** [comment]
I'll adjust so it will give an error on this case as having 0 bams should trigger the help message.
