### ISSUE TITLE
Running indexcov on small input BAMs

### ISSUE THREAD

**Issue by chapmanb** [brentp/goleft#15]
Brent;
I'm running into a goleft indexcov error when running small integration tests with `goleft indexcov`. I'm guessing this is due to the file being too small to have reasonable bins but it would be great if it didn't fail for these edge cases so I don't have to add checks about when to run it. 

Here is a small test case with a `run.sh` to reproduce the problem:
```
wget https://s3.amazonaws.com/chapmanb/testcases/goleft_indexcov_small.tar.gz
```
Let me know if I'm doing anything wrong on my side, looking forward to having these coverage estimates integrated.
```
2017/01/18 14:23:13 indexcov: running on 1 indexes
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/brentp/goleft/indexcov.(*Index).init(0xc4200177d0)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:70 +0x3df
github.com/brentp/goleft/indexcov.(*Index).NormalizedDepth(0xc4200177d0, 0x0, 0x0, 0x40bb, 0x0, 0x30d40, 0x1)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:86 +0x304
github.com/brentp/goleft/indexcov.run(0xc42010a420, 0x2, 0x2, 0xc42000c0d8, 0x1, 0x1, 0xc42010a650, 0x1, 0x1, 0x0, ...)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:315 +0x73c
github.com/brentp/goleft/indexcov.Main()
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:263 +0x99d
main.main()
        /home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:65 +0x191
```

**Comment by brentp** [comment]
thanks for the test-case. This happens because I require at least 2 bins for each chromosome and there arent' that many in this file. I'm updating the code to output: "indexcov: no usable chromsomes in bam"
with a non-zero exit code. This will be in the next release.

**Comment by chapmanb** [comment]
Awesome, thanks for much for digging into this so quickly.

**Comment by brentp** [comment]
by the way, indexcov only needs the bam for the sequence names, so for testing, you can have a .bai that covers, e.g. 100MB and have the .bam that's only the output of `samtools view -H $bam`

**Comment by brentp** [comment]
@chapmanb sorry to stall you on this, but I'd recommend to wait for another release cycle. indexcov got good enough that I got a lot of feedback on improvements. so the usage will change a bit (-d/--directory) instead of (-p/--prefix). The text output should be mostly the same, I just present it the plots differently. So you could proceed, but might be best to wait for another release cycle.

**Comment by chapmanb** [comment]
Thanks Brent, glad to see all the improvements. I'll start up on this one again after the 0.1.11 release is ready. Thanks again for all your work on this.
