### ISSUE TITLE
indexcov 0.1.11 failing on tiny test bam

### ISSUE THREAD

**Issue by astatham** [brentp/goleft#16]
Running the latest release of index cov on this test bam fails
[tiny_bam.zip](https://github.com/brentp/goleft/files/721705/tiny_bam.zip)

    user@d8fb9fcad6fb:/data$ goleft indexcov --directory  tmp/muster/NA12878_TinyTest out/NA12878_TinyTest.dupmarked.realigned.recalibrated.bam
    2017/01/22 04:51:01 indexcov: running on 1 indexes
    2017/01/22 04:51:02 got: 1, principal components
    2017/01/22 04:51:02 indexcov: 1 principal components, not plotting
    panic: runtime error: index out of range

    goroutine 1 [running]:
    github.com/brentp/goleft/indexcov.writeIndex(0xc42023cd50, 0xc420258030, 0x1, 0x1, 0xebfc00, 0x2, 0x2, 0xc4202e0190, 0x1, 0x1, ...)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:541 +0x29f5
    github.com/brentp/goleft/indexcov.Main()
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:288 +0x857
    main.main()
        /home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:64 +0x191
    user@d8fb9fcad6fb:/data$ goleft --version
    goleft Version: 0.1.11

    covmed   : calculate median coverage on a bam by sampling
    depth    : parallelize calls to samtools in user-defined windows
    depthwed : matricize output from depth to n-sites * n-samples
    indexcov : quick coverage estimate using only the bam index

thanks!

**Comment by brentp** [comment]
aye. my testing was focused on mid to large cohorts so there are some errors like this with a single sample where, e.g. PCA makes no sense. I'll get these cleaned up for the next release.
thanks for reporting!

**Comment by brentp** [comment]
I made a pre-release that fixes this here: https://github.com/brentp/goleft/releases/tag/v0.1.12-dev
would be great if you could try it out and let me know any other issues.
The functionality should be solid, but other edge-cases and usability problems are likely to pop up.
