### ISSUE TITLE
goleft indexcov error parsing header on hg38 BAMs

### ISSUE THREAD

**Issue by chapmanb** [brentp/goleft#17]
Brent;
Thanks for the new goleft version. I'm testing on some hg38 runs and getting an issue parsing the BAM reference headers:
```
bash run_header_problem.sh
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/biogo/hts/sam.equalRefs(0xc42028d5e0, 0xc420464bd0, 0xc420466260)
        /home/brentp/go/src/github.com/biogo/hts/sam/reference.go:292 +0x4ad
github.com/biogo/hts/sam.(*Header).AddReference(0xc420132c60, 0xc420464bd0, 0x0, 0x0)
        /home/brentp/go/src/github.com/biogo/hts/sam/header.go:400 +0xbf
github.com/biogo/hts/sam.(*Header).DecodeBinary(0xc420132c60, 0xc640c0, 0xc42015a200, 0x0, 0x0)
        /home/brentp/go/src/github.com/biogo/hts/sam/parse_header.go:72 +0x49b
github.com/biogo/hts/bam.NewReader(0xc64e80, 0xc420108098, 0x2, 0x0, 0x0, 0x110)
        /home/brentp/go/src/github.com/biogo/hts/bam/reader.go:50 +0x115
github.com/brentp/goleft/indexcov.Main()
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:245 +0x302
main.main()
        /home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:64 +0x191
```
Normally the naming on the HLA contigs is the issue since they have both colon and asterisks which can mess up different parsing assumptions:
```
@SQ     SN:HLA-A*01:01:01:01    LN:3503 AH:*
```
Here is a reproducible test case:

https://s3.amazonaws.com/chapmanb/testcases/goleft_indexcov_hg38.tar.gz

Thanks much for looking at this, I need to try to get a biogo development environment setup so I can provide fixes directly.

**Comment by brentp** [comment]
Hi Brad, thanks for the nice test-case.
I opened a PR to biogo to fix this. Surprisingly, it's unrelated to the '*'.
I also so the other test in there where you specified the sex chromosome. I'll come up with a fix for that as well.

**Comment by brentp** [comment]
I made a pre-release here: https://github.com/brentp/goleft/releases/tag/v0.1.12-dev
It also handles --sex argument correctly. 
let me know if you hit anything else.

**Comment by chapmanb** [comment]
Brent -- brilliant, thank you. The 0.1.12-dev version fixes all my issues and runs cleanly on my test cases. Great stuff, I'll work on the next steps of incorporating it into MultiQC plots. Thanks again.
