### ISSUE TITLE
Feature request: option to ignore sex chromosomes?

### ISSUE THREAD

**Issue by roblanf** [brentp/goleft#20]
Great tool - we've been using it to look at coverage on some plant genome samples. One minor issue is that right now we have to specify dummy sex chromosomes. It would be great to have a flag to just ignore that option.

**Comment by brentp** [comment]
that's great to hear. You should just be able to specify `--sex "" ` . If that's not the case with the latest release, let me know and I'll have a look.

**Comment by roblanf** [comment]
Perfect. Works as you said. Thanks for clarifying. Perhaps worth a note in the docs somewhere (though maybe I missed it).

**Comment by brentp** [comment]
good idea. I added a note to the help indicating how to unset like that.

please let me know any other issues like this as I've mostly tested with human data.

**Comment by roblanf** [comment]
will do - so far so good though. Nice docs, binary runs out of the box, etc.

**Comment by roblanf** [comment]
I guess the best thing for non-human analyses here would be to just add something to the error message. I think most people will do what I did, which is copy and paste your example from the readme, and see what happens. 

When I did that, I got the error that goleft couldn't find the X and Y chromosomes. If you added to that error the information on setting ```--sex ""``` to ignore sex chromosomes, that would be really helpful. 

Even better - if you can't find X and Y chromosomes, just ignore sex chromosomes and print a warning?

**Comment by brentp** [comment]
I have made this a warning for now if --sex is the default and neither is found. The warning indicates how to set --sex to avoid the message.
 This will be out in the next release, probably next week. 
Thanks again.
