### ISSUE TITLE
Error in description of bin plot?

### ISSUE THREAD

**Issue by roblanf** [brentp/goleft#21]
In the bin plot description here: 

https://github.com/brentp/goleft/blob/master/docs/indexcov/help-bin.md

you say that samples:

```
* to the left of the plot have many regions with low or missing coverage.
```

Shouldn't that be to the *right* of the plot? (Or maybe I've just totally misunderstood - equally possible).

**Comment by brentp** [comment]
indeed it should. I've updated the help. thanks for reporting.
