### ISSUE TITLE
indexcov: limit to standard chromosomes

### ISSUE THREAD

**Issue by chapmanb** [brentp/goleft#26]
Brent;
Would it be possible to add a general option to limit goleft indexcov output to standard chromosomes (1-22 + gender)? The current GL removal works for GRCh37 but not hg19 or hg38 with `chr` prefixes and won't handle other non-standard alt contigs. I'd be happy to pass a list of chromosomes to the command line so the tool itself doesn't need to hard code these, but it seems like the cur `--chr` option is meant for specifying a single chromosome only. Thanks for any thoughts/suggestions.

**Comment by brentp** [comment]
ok. what is needed for hg38/hg38 Un and random? I could make it default to removing those.

Or I can add `--exclude` that takes a list of chromosomes. 

You're thinking just to remove this from the visual output? Or from the .bed.gz as well?

**Comment by chapmanb** [comment]
Brent;
Here's the gist of the ones from hg38 and hg19 that would be good to drop:

https://gist.github.com/chapmanb/e8b91a7f4426bdfcc0f8a15b7539a7b0

So chrUn, random, hap, alts and HLAs. Removing from everything works great, I don't think we'll be assessing coverage much on these and just creates a bunch of extra.

Alternatively, having a flag for what to include/exclude would be great and I can do myself. `--include` would be easier than `--exclude` to avoid huge command lines on hg38 (or a file of exclude inputs).

Thanks much for considering this.

**Comment by brentp** [comment]
Thanks Brad. I'll make it an exclude pattern with this default:

`^chrEBV$|^NC|_random$|Un_|^HLA\-|_alt$|hap\d$`

that removes all of the chromosomes you sent except chrM. You will be able to set from the command-line if needed, but I think those are sensible defaults. Does that seem reasonable to you?

**Comment by chapmanb** [comment]
That would be perfect -- thanks so much.

**Comment by brentp** [comment]
Hi Brad, I implemented this and pushed a new release. Thanks for the feedback.

**Comment by chapmanb** [comment]
Perfect, thanks so much Brent. I updated the bioconda package for this so it's all rolled out. Much appreciated.
