### ISSUE TITLE
indexcov: incorrect results on chrM / small contig

### ISSUE THREAD

**Issue by pmarks** [brentp/goleft#28]
Wanted to check coverage on hg19/chrM. Ran the following command w/ latest master goleft:
~/code/goleft/bin/goleft indexcov --directory possorted_bam possorted_bam.bam

chrM isn't in the HTML output, even though it doesn't appear to match the default --excludepatt.
chrM does appear in the bed file, but the results seem to be incorrect. Is there a problem getting good results on small chromosomes?

$ zmore possorted_bam/possorted_bam-indexcov.bed.gz | grep chrM
chrM    0       16384   6

$ samtools view possorted_bam.bam chrM:0-20000 | wc -l
212317980

**Comment by brentp** [comment]
the resolution of indexcov is 16KB as that's the resolution in the bam index. chrM is less than this so you'll see a single region (as you do) with a high value since chrM usually has pretty high coverage.
the median coverage across the sample is 1. so in your case, chrM as a whole has at least 6x the coverage of the median region.

**Comment by pmarks** [comment]
@brentp -- sorry, I should have provided more context. chrM has ~200M 75bp reads mapped to it. samtools reports the depth as ~40,000x:

$ samtools depth -r chrM:15100-15110 -d 1000000 possorted_bam.bam
chrM    15100   43754
chrM    15101   42864
chrM    15102   43647
chrM    15103   41952
chrM    15104   42121
chrM    15105   41819
chrM    15106   41127
chrM    15107   42424
chrM    15108   41690
chrM    15109   41589
chrM    15110   41398

**Comment by brentp** [comment]
what is your question?

**Comment by brentp** [comment]
I am guessing your are wondering why the value is only 6? That's the maximum number allowed in indexcov: https://github.com/brentp/goleft/blob/master/indexcov/indexcov.go#L49

remember, this number is unit-less. It's not number of reads. A value of 6 means that the coverage in that 16KB bin is 6X the median bin's coverage.

**Comment by pmarks** [comment]
i see! all is clear. maybe the max should be a parameter, or mentioned in the help text?

**Comment by pmarks** [comment]
the ratio in my case is ~50,000x

**Comment by brentp** [comment]
ok. I'll consider it. I guess for reporting in the BED file it can put the actual value and I can cap at 6 for the plots.

So you  genome-wide average is < 1X? did you target MT?

**Comment by brentp** [comment]
hi @pmarks I just pushed a fix for this so that, on my set, I see depths on MT of:
```
MT	0	16384	9.96	88.1	1.01e+03	1.06e+03	94.7	85	71.8	86.8	159	11665.9	80.4	102	81.6	102	115	136	20.5	166	141	82.5	682	105	124	11.8	79.2	96.9	223	102	97.4	76.4	127	96.7	183	110
```
this will be out in the next release.
thanks for reporting and clarifying.

**Comment by pmarks** [comment]
@brentp - great thanks!
