### ISSUE TITLE
indexcov: producing .html but no other files

### ISSUE THREAD

**Issue by stephenwilliams22** [brentp/goleft#29]
I'm running indexcov on three test .bam files. My code is
`goleft indexcov -d ./ *.bam --sex ''`

I get the following output
`2017/08/09 16:52:39 indexcov: running on 3 indexes`
`2017/08/09 16:52:42 sex chromosomes not found.`
`2017/08/09 16:52:43 got: 3 principal components`
`indexcov finished: see .//index.html for overview of output`

No other files except index.html file are produced and the coverage plots are missing from the .html output. 

The .bam.bai files can be found here https://osf.io/c4bdx/

Any help would be greatly appreciated.

**Comment by brentp** [comment]
before we debug further, can you try with:
```
goleft indexcov -d test-dir *.bam --sex ''
```
and then see if test-dir/index.html works?

**Comment by brentp** [comment]
can you use either: https://github.com/brentp/goleft/releases/download/v0.1.10/anonymize-for-indexcov_linux64
or https://github.com/brentp/goleft/releases/download/v0.1.10/anonymize-for-indexcov_osx depending on your OS and send me a zip of the result. It basically sends in the index and the bam header, which I use for knowing what the chroms, lengths are. and it removes any sample info.

**Comment by stephenwilliams22** [comment]
Hi Brent,
Thanks for the response. I think I have been misinterpreting this command all along. My thought was that the -d option was for the directory of the .bam files not the output directory. It worked now and I'm pretty sure I'm good to go. Sorry for the confusion!

**Comment by brentp** [comment]
ok. well that's good. When you opened the issue, I tested with `-d .` and it worked fine for me so I thought it might be something else.
I'll close for now, but please let me know if you hit other issues.
