### ISSUE TITLE
crai -- panic: runtime error: index out of range

### ISSUE THREAD

**Issue by javierpradom** [brentp/goleft#31]
I am trying to run goleft indexcov on crai files but it doesn't seem to work. Has anyone else found the same problem?

jpm@farm3-head3> goleft_linux64 indexcov --sex "chrX,chrY" -d goleft/ --fai fasta/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa.fai 21772_6.cram.crai
panic: runtime error: index out of range

goroutine 22 [running]:
github.com/brentp/goleft/indexcov/crai.ReadIndex(0xc80c80, 0xc420160580, 0xc420160580, 0x0, 0x0)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/crai/crai.go:159 +0x5f5
github.com/brentp/goleft/indexcov.readIndex(0x7ffe764c7913, 0x11, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:412 +0x5e1
github.com/brentp/goleft/indexcov.Main.func1(0xc4201203c0, 0xc42011fa40, 0x1, 0x1, 0xc4201240a8, 0x1, 0x1, 0xc42011fa50)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:351 +0xaa
created by github.com/brentp/goleft/indexcov.Main
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:356 +0x3b9

**Comment by brentp** [comment]
can you re-index your cram with the latest samtools? There was a bug in the cram indexing in samtools discovered by indexcov that was fixed recently.
If you still see the error after that, can you share the .crai via email?

**Comment by javierpradom** [comment]
Precompiled version was failing and after compiling the source version it worked.
