### ISSUE TITLE
indexcov : won't work with multiple crais

### ISSUE THREAD

**Issue by javierpradom** [brentp/goleft#32]
Works fine with a single crai but appears to fail when running multiple crais. Found this error before?
~/src/go/bin/goleft indexcov -d SEQCAP_WGS_GDAP_Uganda/goleft  --sex "chrX,chrY" --fai fasta/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa.fai 21601_6.cram.crai 21722_8.cram.crai
**panic: runtime error: makeslice: cap out of range**

goroutine 23 [running]:
github.com/brentp/goleft/indexcov/crai.makeSizes(0xc421132f00, 0x1, 0x10, 0xc4204224d8, 0x0, 0x1)
	/nfs/users/nfs_j/jpm/src/go/src/github.com/brentp/goleft/indexcov/crai/crai.go:64 +0x13d
github.com/brentp/goleft/indexcov/crai.(*Index).Sizes(0xc4202a5b20, 0xc4201340f0, 0x50, 0x50)
	/nfs/users/nfs_j/jpm/src/go/src/github.com/brentp/goleft/indexcov/crai/crai.go:48 +0xa6
github.com/brentp/goleft/indexcov.(*Index).init(0xc4201340f0)
	/nfs/users/nfs_j/jpm/src/go/src/github.com/brentp/goleft/indexcov/indexcov.go:80 +0x4cb
github.com/brentp/goleft/indexcov.readIndex(0x7ffd139db8b1, 0x33, 0x0, 0x1, 0x0, 0x0, 0x0)
	/nfs/users/nfs_j/jpm/src/go/src/github.com/brentp/goleft/indexcov/indexcov.go:417 +0x67d
github.com/brentp/goleft/indexcov.Main.func1(0xc42012a3c0, 0xc4202a5ae0, 0x2, 0x2, 0xc4201299f0, 0x2, 0x2, 0xc420129a00)
	/nfs/users/nfs_j/jpm/src/go/src/github.com/brentp/goleft/indexcov/indexcov.go:351 +0xaa
created by github.com/brentp/goleft/indexcov.Main
	/nfs/users/nfs_j/jpm/src/go/src/github.com/brentp/goleft/indexcov/indexcov.go:356 +0x3b9

**Comment by brentp** [comment]
can you make sure that these are generated with samtools 1.5 or greater? to rule out the previous bug in indexing? if you still see it, then please sent the .crai files and I'll get it sorted.

**Comment by javierpradom** [comment]
That seems to solve the problem though some crais with the same samtools version seem to work.

**Comment by brentp** [comment]
yeah, it would be intermittent--not all crai's will have the problematic behavior.

**Comment by brentp** [comment]
as far as I know, there aren't a lot of people using this with crai's, so you may hit some other issues. Please let me know if you do. thanks for following up.
