### ISSUE TITLE
indexcov error

### ISSUE THREAD

**Issue by venuthatikonda** [brentp/goleft#33]
Hi,

I'm trying to run `indexcov` on my WGS samples. Here is the error I got when I execute

```
panic: parsing time "2010-10-19T00:00:00.000+00:00": extra text: +00:00: line 88: "@RG\tID:DKFZ:100630_SN143_0256_A15006043_5\tPL:ILLUMINA\tCN:DKFZ\tPI:353\tDT:2010-10-19T00:00:00.000+00:00\tLB:WGS:DKFZ:ICGC_BL12\tSM:52c198b4-7bda-4f81-8101-a322787a10a6\tPU:DKFZ:100630_SN143_0256_A15006043_5\tPG:fastqtobam"

goroutine 1 [running]:
github.com/brentp/goleft/indexcov.RefsFromBam(0x7fff9331bb5e, 0x48, 0x0, 0x0, 0x1, 0x0, 0xc420174e10)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:294 +0x509
github.com/brentp/goleft/indexcov.getReferences(0x7fff9331bb52, 0xb, 0xc420177001)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:311 +0xb9
github.com/brentp/goleft/indexcov.Main()
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:340 +0x20e
main.main()
        /home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:68 +0x17f
``` 

Is something wrong with BAM files or any dependencies are missing in my machine? Help would be greatly appreciated.

Thank you.

**Comment by brentp** [comment]
can you share that line from the bam header?

**Comment by venuthatikonda** [comment]
Here it is

```
@RG     ID:DKFZ:100630_SN143_0256_A15006043_5   PL:ILLUMINA     CN:DKFZ PI:353  DT:2010-10-19T00:00:00.000+00:00        LB:WGS:DKFZ:ICGC_BL12   SM:52c198b4-7bda-4f81-8101-a322787a10a6     PU:DKFZ:100630_SN143_0256_A15006043_5   PG:fastqtobam
```

**Comment by brentp** [comment]
what's your version of indexcov? looks like this was [fixed in biogo recently](https://github.com/biogo/hts/commit/8bf89f2e2bfa34e19ccb510d0b5ce3f5e8413ba6)

can you download the latest goleft and see if it works for you?

**Comment by venuthatikonda** [comment]
I'm using the version `goleft Version: 0.1.17`.  I think this is the latest release.

**Comment by brentp** [comment]
looking into this now. biogo doesn't like your date format. I have opened an issue there.

**Comment by venuthatikonda** [comment]
Thanks. Let's see what they would say.

**Comment by brentp** [comment]
this was just fixed in biogo. can you try the attached binary?
[goleft_linux64.gz](https://github.com/brentp/goleft/files/1283280/goleft_linux64.gz)

**Comment by venuthatikonda** [comment]
Attached binary is working. Thanks.
