### ISSUE TITLE
indexcov: different coverage scale with cram and bam inputs

### ISSUE THREAD

**Issue by kpalin** [brentp/goleft#36]
With input bam files, the scaled coverage in indexcov is about 1.0 but with cram input the coverage is about 50000.

**Comment by brentp** [comment]
is this for whole genome? can you share a single crai file that has this problem?

**Comment by kpalin** [comment]
It's more complicated than I thought. Sent you two crai files (via funet filesender, you should have the email), one good, one bad.

**Comment by brentp** [comment]
I have found a fix for this. There was a problem with the calculation of median depth for scaling to 1 that only manifested in extreme cases like yours. 

Would you try the attached binary and confirm that this resolves it for you?

thanks for reporting.

[goleft.gz](https://github.com/brentp/goleft/files/1446935/goleft.gz)

**Comment by kpalin** [comment]
Now all crams work but almost all bams don't. Only 2 out of 119 have median value > 10^-5.

**Comment by brentp** [comment]
I fixed a bug that I introduced during that change and neglected to update the binary here. would you mind trying this one?
[goleft.gz](https://github.com/brentp/goleft/files/1450192/goleft.gz)

**Comment by brentp** [comment]
please re-open if the problem persists with latest version.
