### ISSUE TITLE
Interactive indexcov-depth html's missing (and no warning given for 100 input files)

### ISSUE THREAD

**Issue by andreas-wilm** [brentp/goleft#39]
Hi Brent,

I've installed version 0.1.17 as binary and ran indexcov on 100 BAM files (and for testing also on 100 corresponding crai files). I get all expected files except interactive depth html files. indexcov completed without or error or warning. Digging in the code, it seems that maxSamples=100 is a hardcoded cutoff for these files, which is fine (would be nice to have a command line option), but there must be an off by one error, because if it's exactly 100 no warning is printed and no html files are created.

Thanks a lot for goleft!

Andreas

**Comment by brentp** [comment]
I just pushed a fix for this. Thanks for reporting. I'll make a new release in the next week or 2.
