### ISSUE TITLE
Synchronizing depth callable output with bcbio

### ISSUE THREAD

**Issue by chapmanb** [brentp/goleft#4]
Brent;
Thanks again for this implementation. I've got it integrated into bcbio and working on checking differences with current callable calculation output. I found a couple of differences I wasn't able to resolve with my poor golang skills. An example run is here:
```
wget https://s3.amazonaws.com/chapmanb/testcases/goleft_callable.tar.gz
```
when comparing against current bcbio output I get two major differences. The first is that initial blocks defined by the input BED file have an extra base relative the input regions (99 instead of 100 for the first block here):
```
@@ -1,6 +1,6 @@
-chrM   100     1000    CALLABLE
-chrM   2000    5000    CALLABLE
-chr22  14250   14257   LOW_COVERAGE
+chrM   99      1000    CALLABLE
+chrM   1999    5000    CALLABLE
+chr22  14249   14257   LOW_COVERAGE
 chr22  14257   14258   NO_COVERAGE
 chr22  14258   14270   LOW_COVERAGE
 chr22  14270   14277   CALLABLE
```
This is caused by the `-1` when retrieving from the cache, but I couldn't figure out the right way to push these initial blocks onto the cache with a `+1` for the start.

The second is that the depth output is missing some `NO_COVERAGE` regions. I guess this is due to not using `-a` for depth:
```
@@ -15,6 +15,5 @@
 chr22  14487   14495   LOW_COVERAGE
 chr22  14495   14496   CALLABLE
 chr22  14496   14595   LOW_COVERAGE
-chr22  14595   15068   NO_COVERAGE
 chr22  15068   15128   LOW_COVERAGE
 chr22  15128   15500   CALLABLE
```
Thanks for any thoughts and suggestions.

**Comment by brentp** [comment]
Hi Brad, thanks again for the test-case. I've just pushed a fix.

I will have a closer look this evening. There may be still a problem if, the end of the region has no coverage but it resolves the cases you have here.

I'm going to add your files as a test-case if you don't mind.

**Comment by brentp** [comment]
Callable looks good, but there are still some issues with depth. I'll ping this issue when I have a chance to fix.

**Comment by brentp** [comment]
Hi Brad, I think this is now all working as expected. Could you check to make sure it matches what you see from bcbio? I changed the windows.bed to this:
```
chr22	14250	15500
chr22	20000	22000
chrM	100	1000
chrM	2000	5000
```
to make sure that stuff is reported for all regions of 0 coverage.


The remaining things to keep in mind that are open for discussion:

1) the parallelization can result in out-of-order files. I can change this, but I think it's simple enough to sort post-hoc
2) for genomic coverage, if you specify a bed file that is the full chromosome (as you do in bcbio last I saw), it will still only parallelize by chromosome. It either takes a bed and splits on the intervals in the bed or takes a full genome and splits into 5MB sections. Do you think I should check if the regions of the bed and split if the are longer than 5MB?
3) a related problem to above is that, when splitting the genome into 5MB chunks, it won't merge the depth at the end of once chunk with that from the previous chunk even if they have the same value for callable.

Finally, is there a reason you use: `max(args.MaxMeanDepth+1000, 8000)` as the argument to samtools depth? Seems like this could just be args.MaxMeanDepth + 10000.

**Comment by chapmanb** [comment]
Thanks Brent, awesome. I'll give this a try first thing tomorrow. To answer your questions:

1. We should be able to feed these to gsort so that's not a problem from my side.
2. I'll split the whole genomes when feeding them to goleft (and already have this implemented) so you don't need to do anything.
3. That should work fine, thanks.
4. I was only keeping the default (8000) if MaxMeanDepth is lower but your suggestion works as well so I don't mind.

Thanks again for all this.

**Comment by brentp** [comment]
For 1. I pushed an option (-o) that will keep the output sorted. It should have very little overhead so will be interesting to see how it compares to gsort.

I changed 4. to be MaxMeanDepth+1000.

I'll make a release if everything looks good to you tomorrow.

**Comment by chapmanb** [comment]
Brent;
Thanks so much for the ordered option and all the fixes. All looks good now except for one issue with the `NO_COVERAGE` block we were missing in the test case. goleft depth output looks like:
```
chr22   14496   14595   LOW_COVERAGE
chr22   14594   15069   NO_COVERAGE
chr22   15068   15128   LOW_COVERAGE
```
where it should be:
```
chr22   14496   14595   LOW_COVERAGE
chr22   14595   15068   NO_COVERAGE
chr22   15068   15128   LOW_COVERAGE
```
It looks like goleft has an extra -1/+1 pad on either side of the middle interval. Beyond that things are looking great. Thanks again for all the help with this.

**Comment by brentp** [comment]
Fixed. Cheers.

**Comment by chapmanb** [comment]
Brent -- perfect, thank you. All looks great to me now, this is brilliant. Once we ship a new version I'll update bcbio and we can test at scale.

**Comment by brentp** [comment]
I pushed binaries to v0.1.1
