### ISSUE TITLE
Installation & integration with STRetch

### ISSUE THREAD

**Issue by jbsysadmin** [brentp/goleft#46]
Greetings. I was tasked with installing STRetch (https://github.com/Oshlack/STRetch/wiki/Installing-STRetch) This "goleft" is listed as a dependency. 

Given a Python 3 at <directory>/python3.6.1/, how does one install this? I am not using Conda. Is this a Python module, or standalone? Is there source that can be compiled with configure & make, with the output in PATH at the time STRetch is used? 

Environment is Centos 6.9.

**Comment by brentp** [comment]
does this: https://github.com/brentp/goleft#installation
answer your question?

**Comment by brentp** [comment]
goleft is a static binary. I'm closing this. Feel free to open if you have more info.
