### ISSUE TITLE
indexcov returns "no reference stats found"

### ISSUE THREAD

**Issue by tdelhomme** [brentp/goleft#49]
Hi Brent,
I try to run `goleft indexcov` on two small BAM files, that we store on GitHub [here](https://github.com/IARCbioinfo/data_test/tree/master/BAM).
But unfortunately I get this error (I cutted it, first line below is repeated from 0th to 85th):

```
2018/10/10 15:07:33 no reference stats found for 79th reference
2018/10/10 15:07:33 no reference stats found for 80th reference
2018/10/10 15:07:33 no reference stats found for 81th reference
2018/10/10 15:07:33 no reference stats found for 82th reference
2018/10/10 15:07:33 no reference stats found for 83th reference
2018/10/10 15:07:33 no reference stats found for 84th reference
2018/10/10 15:07:33 no reference stats found for 85th reference
2018/10/10 15:07:33 indexcov: running on 1 indexes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8568f6]

goroutine 1 [running]:
github.com/brentp/goleft/indexcov/crai.(*Index).Sizes(0x0, 0x0, 0x0, 0x0)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/crai/crai.go:46 +0x26
github.com/brentp/goleft/indexcov.(*Index).init(0xc0001a6410)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:83 +0x471
github.com/brentp/goleft/indexcov.(*Index).NormalizedDepth(0xc0001a6410, 0x0, 0x30d40, 0xc00038e000, 0x0)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:124 +0x1ed
github.com/brentp/goleft/indexcov.run(0xc0002ac000, 0x56, 0x80, 0xc0000de0d0, 0x1, 0x1, 0xc00019e6a0, 0x1, 0x1, 0xc00034c580, ...)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:559 +0x829
github.com/brentp/goleft/indexcov.Main()
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:402 +0x51e
main.main()
	/home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:68 +0x179
```

I have no idea about what is happening here...

**Comment by tdelhomme** [comment]
I am using latest version `0.2.0`

**Comment by brentp** [comment]
hmm. this should work but those bams have so little data that it's causing a lot of problems. I fixed the first one, but then it's essentially all empty for the plots and that creates further problems. I'll see if I can fix entirely, but I think this is pretty unlikely to occur on real data. Thanks for providing test data.

**Comment by tdelhomme** [comment]
Thanks for your answer! It would be super cool to fix it, I need to run this on small BAMs in my CI tests...

**Comment by brentp** [comment]
for indexcov, you can provide the original bai (for the full bam) along with a truncated or small bam like the ones you have. if that works for the rest of your testing, then you could do that without waiting on me to fix.

**Comment by brentp** [comment]
Here is a binary that fixes this. The next release might not be out for a few weeks.
[goleft_dev.gz](https://github.com/brentp/goleft/files/2465242/goleft_dev.gz)

**Comment by tdelhomme** [comment]
great! Thanks a lot.
