### ISSUE TITLE
How to generate the X-Y plots?

### ISSUE THREAD

**Issue by GreeshmaThulasi** [brentp/goleft#50]
Hi all,
I have some bam files and corresponding bai files (of unknown gender).
I used the indexcov function. But didn't get any X-Y plot. **What are the arguments to be supplied for generating X-Y plot**. Getting some error as:
`ngslab@ngslab-OptiPlex-3050:~/Downloads/goleft-master/indexcov/input$ goleft indexcov --directory /home/ngslab/Downloads/goleft-master/indexcov/ '/home/ngslab/Downloads/goleft-master/indexcov/input/NA-180.bam' 
2018/10/19 16:18:02 indexcov: running on 1 indexes
2018/10/19 16:18:04 indexcov: found chromosome "chrX", wanted "X" please use exact chromosome names for --sex.
2018/10/19 16:18:04 indexcov: found chromosome "chrY", wanted "Y" please use exact chromosome names for --sex.
(WARNING) indexcov: expected 2 sex chromosomes, found: 0.
you can set the expected with --sex ''
2018/10/19 16:18:04 sex chromosomes not found.
2018/10/19 16:18:04 got: 1 principal components
2018/10/19 16:18:04 indexcov: 1 principal components, not plotting
indexcov finished: see /home/ngslab/Downloads/goleft-master/indexcov//index.html for overview of output
`
Please help me to resolve the issue.

**Comment by brentp** [comment]
you can use `--sex "chrX,chrY"` to set the sex chromosomes. 
if I can make that message clearer, please advise.

**Comment by GreeshmaThulasi** [comment]
Hi @Brent,
Thanks for the help.


*Thanks with regards,*

*Greeshma Thulasi*
