### ISSUE TITLE
ndexcv: excluding chromosome: NC_031965 because of exclude-pattern: ^chrEBV$|^NC|_random$|Un_|^HLA\-|_alt$|hap\d

### ISSUE THREAD

**Issue by astridboehne** [brentp/goleft#56]
Hi Brent
I tried to run indexcov on my bam files but it excludes all my chromosomes but one which has a different naming.
I am working with an NCBI reference genome and chromosomes are named NC_12344. How can I overwrite the default setting which excludes this pattern?
I tried this way:
./goleft_linux64 indexcov --chrom NC_031983 --directory /scicore/home/salzburg/boehne/test/ /scicore/home/salzburg/boehne/*realn.bam
which did nor work and the same command without the --chrom flag
Any help would be great
Thanks
Astrid

**Comment by brentp** [comment]
Just set a new exclude pattern like:
```
--excludepatt "ZZZZZZ"
```
that won't match anything.

**Comment by astridboehne** [comment]
perfect, thank you, solved the issue
