### ISSUE TITLE
error: bam is required 

### ISSUE THREAD

**Issue by clersdom** [brentp/goleft#59]
I am trying to run golfeft indexcov and seems to not be finding the bam files. For my data I have only the bam and bai files. I am now testing if it works for the `test-data/` provided in GitHub and I have the same issue. 

I am running:
`./goleft_linux64.dms indexcov --directory test-data/ *.bam`

And getting the error:
`2019/08/13 11:06:56 ERROR: since no .fai was specified, expected input to be a list of bams
2019/08/13 11:06:56 ERROR: got, e.g. *.bam
panic: open *.bam: no such file or directory

goroutine 1 [running]:
github.com/brentp/goleft/indexcov.RefsFromBam(0x7ffd95327ff1, 0x5, 0x0, 0x0, 0xffffffffffffff9c, 0xc0000cdbb8, 0x49d619)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:317 +0x4b6
github.com/brentp/goleft/indexcov.getReferences(0x7ffd95327fe6, 0xa, 0xc0001b2f01)
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:338 +0xbe
github.com/brentp/goleft/indexcov.Main()
        /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:388 +0x1e6
main.main()
        /home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:68 +0x179
`

I have also the latest version
goleft Version: 0.2.1

Thanks in advance.

**Comment by brentp** [comment]
there are no bams in that directory.
what does `ls *.bam` show in the directory where you ran the command?

**Comment by clersdom** [comment]
cd test-data/

`ls *.bam`
sample_issue_27_0001.bam

To clarify, I am running `Indexcov` that contains the folder `test-data/` with the bam `sample_issue_27_0001.bam`

**Comment by brentp** [comment]
then instead of `./goleft_linux64.dms indexcov --directory test-data/ *.bam`
you need to run:
```
./goleft_linux64.dms indexcov --directory test-data/ test-data/*.bam
```

**Comment by clersdom** [comment]
Great, it is working now. I thought the directory was already specifying where the `.bam` files are. 
Thanks for the fast help!
