### ISSUE TITLE
suggestion: zoomable chromosome depth plots in indexcov

### ISSUE THREAD

**Issue by edg1983** [brentp/goleft#62]
Hi brent,

I have a suggestion for indexcov chromosome coverage plots. Is it possible to make them zoomable? Something like a plotly-generated plot?
This would be great to inspect coverage for small regions, small deletion CNVs for example.

Thanks!
Edoardo

**Comment by brentp** [comment]
hi, this is possible with covviz: https://github.com/brwnj/covviz which takes `indexcov` output.
