### ISSUE TITLE
indexcov shows stepwise coverage distribution

### ISSUE THREAD

**Issue by mattsoup** [brentp/goleft#63]
Hi,

We've run into an odd issue where indexcov shows a sort of stepwise coverage pattern, like so:

![goleft_indexcov-roc-plot-2](https://user-images.githubusercontent.com/28735187/77462869-14a75f00-6ddb-11ea-98e7-8fdc29d79b8f.png)

In contrast, the same data analyzed with mosdepth shows a more expected pattern:

![chr1_mosdepth_covg](https://user-images.githubusercontent.com/28735187/77462674-d4e07780-6dda-11ea-9494-228f259c16eb.png)

Our interpretation of the indexcov graph would be that there are discrete bins of coverage values, which the mosdepth graph doesn't support. Could there be something other than some technical factor that would cause this pattern?

Thanks

**Comment by brentp** [comment]
can you share the original indexcov html, rather than the multiqc? that would help to determine that it's in indexcov rather than something about multiqc.

**Comment by mattsoup** [comment]
Here's the .png, if that'll be sufficient?

![1_merged sorted bam-indexcov-roc-chr1](https://user-images.githubusercontent.com/28735187/77464458-94cec400-6ddd-11ea-950c-0df889aaca50.png)

**Comment by brentp** [comment]
this is odd.

i would guess it;s because of the relatively low coverage and the lack of resolution in the indexcov data. i would say it's safe to ignore this as an indexcov artefact.

**Comment by mattsoup** [comment]
Yep, here's data from chr17 from one replicate:

![1_merged sorted bam-indexcov-roc-chr17](https://user-images.githubusercontent.com/28735187/77474370-5b9e5000-6ded-11ea-91fb-d6ab2174ae34.png)

And from chr17 from two replicates merged together, so there's higher coverage:

![chr17-indexcov-roc-chr17](https://user-images.githubusercontent.com/28735187/77474391-678a1200-6ded-11ea-8bcf-7e878e412082.png)

So I guess the low-ish coverage is the main driver of the step pattern. Thanks for the help!
