### ISSUE TITLE
Feature request: New option --exclude for covstats

### ISSUE THREAD

**Issue by YiweiNiu** [brentp/goleft#64]
Hi Brent,

Thanks for Goleft! I would like to propose a new option for `goleft covstats`: `--exclude` to be able to exclude chromosomes. In some cases, I want to exclude some chromosomes when generating coverage stats.

Thanks,
Yiwei

**Comment by brentp** [comment]
this is a reasonable request, but it is unlikely that i will add it. [mosdepth](https://github.com/brentp/mosdepth) is so fast now that you can get flexible coverage information in very short time. covstats is for the case where you want a quick check.

i would accept a pull request that implements this feature.

**Comment by YiweiNiu** [comment]
Thank you for your reply! I would try `mosdepth`.
