### ISSUE TITLE
Running Indexcov on cram files with different paths

### ISSUE THREAD

**Issue by Saeideh-Ashouri** [brentp/goleft#69]
Dear @brentp 

I would like to run Indexcov on more than 11,000 human genomes (in CRAM format) each located in a separate path. 
My first question is how should I specify .crai files as input for indexcov? (I mean how to show the path to many .crai files to indexcov? Is it possible to make a file containing path to all those files?)
And my second question is for running indexcov on batches, how many samples (maximum number) would you recommend me consider in each batch?

Best,
Saeideh

**Comment by brentp** [comment]
Hi, you can use your shell expansion to get the list of crais, e.g.:
```
goleft indexcov --extranormalize --directory my-cohort -f $fai /path/to/*/*.crai /other/path/to/*/*.crai
```
and that's how you can run with crai files as well (note the --extranormalize which is very useful for crai files).

You can probably run on batches of 3000-4000 samples at a time. It might work with 11,000, but will stress your browser when you view the results.
Let me know if you have more questions.

**Comment by Saeideh-Ashouri** [comment]
Dear @brentp 

Thank you so much for your prompt reply.
And thank you for indexcov. It was quite helpful.

Here I close this issue. 
Best,
Saeideh
