### ISSUE TITLE
indexcov: usage with long reads ?

### ISSUE THREAD

**Issue by colindaven** [brentp/goleft#71]
Hi, 

would you expect this to work for long reads ? The scaling looks great in your png example, with most values around 1.

I see most values are low and distinctly diverged from one. These are ONT  data of about 100X coverage, which I guess might be too long for the index windows to be reliably calculated ?

Otherwise the indexcov tool worked first time, thanks.

```
#chrom	cov	T14-sorted
chr1	0.00	1.00
chr1	0.02	0.49
chr1	0.04	0.48
chr1	0.06	0.47
chr1	0.09	0.46
chr1	0.11	0.45
chr1	0.13	0.44
chr1	0.15	0.42
chr1	0.17	0.42
chr1	0.19	0.41
chr1	0.21	0.40
chr1	0.24	0.39
chr1	0.26	0.38
chr1	0.28	0.37
chr1	0.30	0.36
chr1	0.32	0.35
chr1	0.34	0.34
chr1	0.36	0.33
chr1	0.39	0.33
chr1	0.41	0.32
chr1	0.43	0.31
chr1	0.45	0.29
chr1	0.47	0.28
chr1	0.49	0.28
chr1	0.51	0.27
chr1	0.54	0.26
chr1	0.56	0.25
chr1	0.58	0.24
chr1	0.60	0.23
chr1	0.62	0.22
chr1	0.64	0.21
chr1	0.66	0.21
chr1	0.69	0.20
chr1	0.71	0.19
```

**Comment by brentp** [comment]
Yes, with long reads, it's harder to get enough data in each bin. I would expect it to be still informative--but not too surprised if it's off. You could try running mosdepth --fast which should be quite ... fast for long reads and then use [covviz](https://github.com/brwnj/covviz) to view the results.
