### ISSUE TITLE
Release Linux aarch64 binary

### ISSUE THREAD

**Issue by martin-g** [brentp/goleft#75]
I'd like to request a release of Linux ARM64/Aarch64 binary in addition to the Linux x86_64 and Mac OSX Intel ones.

Since few months Bioconda officially supports `linux-aarch64`.
Currently the recipe uses the released binaries - https://github.com/bioconda/bioconda-recipes/blob/master/recipes/goleft/meta.yaml#L8-L11. I could add logic to build from sources if needed too!

**Comment by brentp** [comment]
Hi @martin-g , I am happy to add this. Do I simply use this:
```
CGO_ENABLED=0 GOARCH=arm64 go build -o goleft_arm64 --ldflags '-extldflags "-static"' cmd/goleft/goleft.go
```
to compile? I think that will build for linux/arm64. Not sure if the OS matters.

**Comment by martin-g** [comment]
https://github.com/brentp/vcfanno/releases/download/v0.3.5/vcfanno_linux_aarch64 - here you used `aarch64` as a suffix.
I think it is a better suffix for Linux. You can use `arm64` for darwin (Mac OS) later if requested.

**Comment by brentp** [comment]
ok. I just added it to the existing release: https://github.com/brentp/goleft/releases/tag/v0.2.6

thanks for bringing this up and for the help!
