### ISSUE TITLE
crai resolution in output-indexcov.bed.gz

### ISSUE THREAD

**Issue by corinsexton** [brentp/goleft#77]
Hi there,

I'm running indexcov on around 2,000 crai files and I had a quick question about the resolution within the output-indexcov.bed.gz file. I see that the windows are the standard 16,384bp that are used for bam indices. Is this the expected behavior for indexcov when using cram indices as well?

Thanks!

**Comment by brentp** [comment]
hi,
yes this is expected. It interpolates to the same window size even though the cram index resolution is different and often much lower.

**Comment by corinsexton** [comment]
Got it. So in your experience would it be appropriate to filter out low quality samples based on the bin counts generated from crai files? Or is that too much of a stretch with the low resolution?

**Comment by brentp** [comment]
It's hard to make a blanket statement, but usually if you look at the html output and there are outliers, it's worth looking into those further.

**Comment by corinsexton** [comment]
That makes sense. Thanks for all the clarifications!
