### ISSUE TITLE
Sambamba Comparison

### ISSUE THREAD

**Issue by dnbh** [brentp/goleft#8]
Have you compared goleft to Sambamba?

There are a few small issues with it in terms of flexibility, but would you say goleft performs better or provides orthogonal functionality? (For example, one issue is that sambamba view can't take bitwise flags, unlike samtools view.)

**Comment by dnbh** [comment]
Sorry, my brain's not working; I'm up too late. Sambamba doesn't do coverage.

**Comment by brentp** [comment]
No problem. You can see the discussion in bcbio that led to this version of goleft depth here: https://github.com/chapmanb/bcbio-nextgen/issues/1549

It would be nice to support flags, but, for now, goleft depth can do a 30X whole genome coverage in < 15 minutes with 32 cpus.

**Comment by dnbh** [comment]
Good work!

While I'm at it, I've been using GNU Parallel for my needs, and it pretty seamlessly handles as many cores and machines as I'd like it to, while having very flexible inp

**Comment by brentp** [comment]
I doubt there's much difference in the efficiency, but gargs may be a bit faster. I've never needed much of the extras in gnu parallel, but I know it has a lot more features. 
I have plans to add a bit more features to gargs, but it actually covers most of my needs as-is. And the backing library: https://godoc.org/github.com/brentp/gargs/process is nice inside of go projects that make system calls.
